### ISSUE TITLE
Project 6

### ISSUE THREAD

**Issue by karnaksp** [s21NameSpace/CT-06#1]
Коммуникация – важнейшая часть нашей жизни. И любая коммуникация имеет цель. 
В этом проекте ты узнаешь, как, используя инструменты коммуникации:

1. Управлять своими результатами работы.
2. Выстроить эффективные рабочие отношения с руководителем.
3. Выстроить отношения с коллегами, от которых может зависеть твоя работа.

В этом проекте ты научишься:

- ставить цели и планировать результаты;
- управлять коммуникацией с руководителем;
- выстраивать коммуникацию с коллегами.

Литература:

[Перечень навыков soft-skills и способы их развития](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/karnaksp/MY_SCHOOL_PROJECTS/Career/CT06-1/materials/%D0%9F%D0%B5%D1%80%D0%B5%D1%87%D0%B5%D0%BD%D1%8C_%D0%BD%D0%B0%D0%B2%D1%8B%D0%BA%D0%BE%D0%B2_.pdf).
[Как построить идеальные отношения с начальником](https://prosto.rabota.ru/post/idealno-s-nachalnikom/).
[Как построить идеальные отношения с коллегами](https://prosto.rabota.ru/post/idealnye-otnosheniya-s-kollegami/).
«Правила карьеры. Все, что нужно для служебного роста» Темплар Ричард.

**Comment by karnaksp** [comment]
Выполняя этот проект, создай свою ветку репозитория, выполни задачи, скопируй эту форму со своим ником и добавь комментарий ниже. Отметь галочками, что сделано:

Проект **karnaksp**

### Управление результатом
Пример задачи, полученной от руководителя: исправить орфографическую ошибку в интерфейсе программы.
- [x] Напиши письмо руководителю для выяснения деталей о решении этой задачи


### Управление отношениями с руководителем

- [x] Составь письмо руководителю с запросом на встречу по обратной связи.
- [x] Что можно узнать о себе на сессии обратной связи? 5 пунктов.

### Выстраивание отношений с коллегами

- [x] Какие действия ты можешь предпринять, чтобы выстроить комфортные отношения с коллегами?
- [x] Что делать, если отношения с важным коллегой не выстраиваются?
- [x] Что делать, если с коллегой конфликт?

Когда задача будет выполнена, тэгни меня так @karnaksp , чтобы я зафиксировал, что эту задачу можно закрыть и отправиться на ретроспективу.

**Comment by Hultyrhik** [comment]
Выполняя этот проект, создай свою ветку репозитория, выполни задачи, скопируй эту форму со своим ником и добавь комментарий ниже. Отметь галочками, что сделано:

Проект **higagarr**
Управление результатом

Пример задачи, полученной от руководителя: исправить орфографическую ошибку в интерфейсе программы.

- [x]     Напиши письмо руководителю для выяснения деталей о решении этой задачи

Управление отношениями с руководителем

- [x] Составь письмо руководителю с запросом на встречу по обратной связи.
- [x]     Что можно узнать о себе на сессии обратной связи? 5 пунктов.

Выстраивание отношений с коллегами

- [x] Какие действия ты можешь предпринять, чтобы выстроить комфортные отношения с коллегами?
- [x] Что делать, если отношения с важным коллегой не выстраиваются?
- [x] Что делать, если с коллегой конфликт?

**Comment by Hultyrhik** [comment]
@karnaksp Сделал, добавил свои проекты в ветку higaharr

**Comment by karnaksp** [comment]
@lobanovivanphantom тут еще тебя ждем

**Comment by karnaksp** [comment]
провел уже ретроспективу
